<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rqlite.Internal</RootNamespace>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rqlite.Internal\Rqlite.Internal.csproj" />
  </ItemGroup>
</Project>
